name: continuous integration

on:
  - push

jobs:
  lint_frontend:
    runs-on: ubuntu-latest
    env:
      HEDERA_ACCOUNT_ID: ${{ secrets.HEDERA_ACCOUNT_ID }}
      HEDERA_PRIVATE_KEY: ${{ secrets.HEDERA_PRIVATE_KEY }}
      HEDERA_ENVIRONMENT: ${{ vars.HEDERA_ENVIRONMENT }}
      PUBLIC_HASHCONNECT_PROJECT_ID: ${{ vars.PUBLIC_HASHCONNECT_PROJECT_ID }}
      PUBLIC_DEPLOYMENT_CONTRACT_ID: ${{ vars.PUBLIC_DEPLOYMENT_CONTRACT_ID }}
      PUBLIC_DEPLOYMENT_NFT_TOKEN_ID: ${{ vars.PUBLIC_DEPLOYMENT_NFT_TOKEN_ID }}
      PUBLIC_IPFS_GATEWAY_BASE_URL: ${{ vars.PUBLIC_IPFS_GATEWAY_BASE_URL }}
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"
      - run: pnpm install
      # script
      - run: pnpm -C frontend lint:eslint
      - run: pnpm -C frontend lint:prettier
      - run: pnpm -C frontend lint:svelte

  build_frontend:
    runs-on: ubuntu-latest
    env:
      HEDERA_ACCOUNT_ID: ${{ secrets.HEDERA_ACCOUNT_ID }}
      HEDERA_PRIVATE_KEY: ${{ secrets.HEDERA_PRIVATE_KEY }}
      HEDERA_ENVIRONMENT: ${{ vars.HEDERA_ENVIRONMENT }}
      PUBLIC_HASHCONNECT_PROJECT_ID: ${{ vars.PUBLIC_HASHCONNECT_PROJECT_ID }}
      PUBLIC_DEPLOYMENT_CONTRACT_ID: ${{ vars.PUBLIC_DEPLOYMENT_CONTRACT_ID }}
      PUBLIC_DEPLOYMENT_NFT_TOKEN_ID: ${{ vars.PUBLIC_DEPLOYMENT_NFT_TOKEN_ID }}
      PUBLIC_IPFS_GATEWAY_BASE_URL: ${{ vars.PUBLIC_IPFS_GATEWAY_BASE_URL }}
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"
      - run: pnpm install
      # script
      - run: pnpm -C frontend build
